### ISSUE TITLE
Add support for trick screenshots

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/octobertricks.com#7]
This would make clearer what a trick does.

**Comment by aniket-magadum** [comment]
Is anyone working on this?

**Comment by tobias-kuendig** [comment]
I am not.

This could be impemented as a first version using the [Responsiv.Uploader](https://octobercms.com/plugin/responsiv-uploader) plugin. This won't allow screenshots in the content itself but they could be displayed above or below the content.

**Comment by LarBearrr** [comment]
Would be great to figure out copy/paste behavior right in the editor, like github. I'll do some looking into it!

**Comment by SamDeny** [comment]
Hello there.

I know, this topic is a bit older... but... anyways...

EasyMDE already provides the possibility to upload images since version 2.8.0 (released in 2019). However, I created a quick prototype how it could work and came along with the following solution (The component method, shown below, still misses some validation stuff like filesize, mimetype and so on).

The EasyMDE related JavaScript code (I updated EasyMDE to the latest version)
```js
var easyMDE = new EasyMDE({
    showIcons: ['strikethrough', 'code', 'upload-image'],
    hideIcons: [],
    element: document.querySelector('#trick_content'),
    toolbar: [
        "bold", "italic", "strikethrough", "heading", "|", 
        "code", "quote", "unordered-list", "ordered-list","|", 
        "link", "image", "upload-image","|", 
        "preview", "side-by-side", "fullscreen","|", 
        "guide"
    ],
    uploadImage: true,
    imageUploadFunction: (file, resolve, reject) => {
        jQuery(this).request('onUploadImage', {
            data: {
                'image': file
            },
            files: true,
            success: function (data) {
                if (typeof data === 'object' && (data.status || '') === 'success') {
                    resolve(data.path);
                } else {
                    reject('An unknown error occured');
                }
            },
            error: function () {
                let message = (this.responseJSON || {}).result || 'An unknown error occured';
                reject(message);
            }
        });
    },
    renderingConfig: {
        singleLineBreaks: false,
        codeSyntaxHighlighting: true,
    },
});
```


The required method on the TrickForm component:
```php
public function onUploadImage()
{
    if (!Input::hasFile('image')) {
        throw new AjaxException('The passed form is invalid.');
    }

    try {
        $file = new File();
        $file->fromPost(request()->file('image'));
        $file->save();
        return ['status' => 'success', 'path' => $file->getPath()];
    } catch (\Exception $e) {
        throw new AjaxException($e->getMessage());
    }
}
```

Anyways, one issue stays: What happens when the user aborts the Trick creation, after uploading x pictures? I've two solution for this scenario.

1. Each file is referenced via the `system_files` db. Theoretically, we could clean unused images by checking the `field` or `attachment_id` / `attachment_type` columns and remove them respectively. This can either happen manually via the backend or using a cronjob.

2. Alternatively, we "skip" the upload path on the EasyMDE function and handle them after the user submits the Trick itself. This **should** be possible with some JavaScript magic and a simple replacement on the backend side. However, this COULD be a horrible user experience when the user uploads huge or many images (which both could be restricted, of course).

Anyways. Would do you think?

~Sam.
